"""empty message

Revision ID: a23df4a61ce9
Revises: 96ee38a763bc
Create Date: 2023-12-15 15:06:35.446533

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a23df4a61ce9'
down_revision = '96ee38a763bc'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Product_id', table_name='Product')
    op.drop_index('ix_Product_name', table_name='Product')
    op.drop_table('Product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['User.id'], name='Product_created_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Product_pkey')
    )
    op.create_index('ix_Product_name', 'Product', ['name'], unique=False)
    op.create_index('ix_Product_id', 'Product', ['id'], unique=False)
    # ### end Alembic commands ###
